CREATE TABLE [dbo].[tblCaregiver]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [FirstName] VARCHAR(50) NOT NULL, 
    [LastName] VARCHAR(50) NOT NULL, 
    [City] VARCHAR(50) NOT NULL, 
    [State] CHAR(2) NOT NULL, 
    [PhoneNumber] VARCHAR(22) NOT NULL, 
    [UserId] UNIQUEIDENTIFIER NOT NULL UNIQUE
)
