CREATE TABLE [dbo].[tblMedicationTime]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [PillTime] TIME NOT NULL, 
    [MedicationId] UNIQUEIDENTIFIER NOT NULL, 
    [PatientId] UNIQUEIDENTIFIER NOT NULL
)
